#!/usr/bin/env bash
# shellcheck shell=bash
#
# Bamboo-Site — Nginx configuration generation and safe activation.
#
# The workspace file <workspace>/nginx/<domain>.conf is the source of truth.
# /etc/nginx only ever holds symlinks into it:
#
#   /etc/nginx/sites-available/<domain>.conf -> /var/www/<domain>/nginx/<domain>.conf
#   /etc/nginx/sites-enabled/<domain>.conf   -> ../sites-available/<domain>.conf
#
# Every activation runs `nginx -t` first and rolls back to the previous file if
# the test fails, so a bad config can never take the server down.

nginx_ensure_limits() {
    # The rate-limit zones must live in an http-context file; server blocks
    # reference them by name.
    local file="$BAMBOO_NGINX_LIMITS_FILE" content
    content="$(cat <<'EOF'
# Managed by Bamboo-Site - shared zones for per-site rate limiting.
# Referenced by every generated server block; keep the zone names.
limit_req_zone $binary_remote_addr zone=bamboo_req:10m rate=20r/s;
limit_conn_zone $binary_remote_addr zone=bamboo_conn:10m;
EOF
)"
    if [ -f "$file" ] && [ "$(cat "$file" 2>/dev/null)" = "$content" ]; then
        log_debug "Rate-limit zones already current: $file"
        return 0
    fi
    if bamboo_is_dry_run; then
        log_info "[dry-run] would write $file"
        return 0
    fi
    printf '%s\n' "$content" | atomic_write "$file"
    log_ok "Nginx rate-limit zones written to $file."
    return 0
}

nginx_http2_listen_lines() {
    # `listen ... http2` is deprecated from nginx 1.25.1 (the `http2` directive
    # replaces it), so emit whichever form the installed version understands.
    local version='1.18.0'
    if [ "$BAMBOO_TEST_MODE" != "1" ]; then
        bamboo_try bamboo_nginx_bin -v
        version="$(printf '%s' "$BAMBOO_LAST_OUTPUT" | sed -n 's|^nginx version: nginx/||p' | head -n 1)"
        [ -n "$version" ] || version='1.18.0'
        version="${version%% *}"
    fi
    if bamboo_version_ge "$version" '1.25.1'; then
        printf '    listen 443 ssl;\n'
        printf '    listen [::]:443 ssl;\n'
        printf '    http2 on;\n'
    else
        printf '    listen 443 ssl http2;\n'
        printf '    listen [::]:443 ssl http2;\n'
    fi
}

nginx_emit_security_headers() {
    local hsts="${1:-0}"
    cat <<'EOF'
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
EOF
    if [ "$hsts" = "1" ]; then
        printf '    add_header Strict-Transport-Security "max-age=31536000" always;\n'
    fi
    return 0
}

nginx_emit_common_locations() {
    local domain="$1" root
    root="$(workspace_public "$domain")"
    cat <<EOF

    # --- Security: ACME stays reachable, hidden/sensitive files never are ---
    location ^~ /.well-known/acme-challenge/ {
        root $root;
        default_type "text/plain";
        allow all;
    }

    location ~ /\.(?!well-known) {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* \.(?:env|git|gitignore|svn|hg|bak|old|orig|save|swp|swo|sql|sqlite|log|ini|conf|dist|lock|ya?ml)\$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~* /(?:composer\.(?:json|lock)|package(?:-lock)?\.json|yarn\.lock|pnpm-lock\.yaml|Dockerfile|docker-compose\.ya?ml|\.htaccess|\.htpasswd|web\.config|Makefile)\$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    # --- Performance: six-month cache for immutable static assets ---
    location ~* \.(?:css|js|mjs|map|jpg|jpeg|png|gif|webp|avif|ico|svg|bmp|woff2?|ttf|otf|eot|mp4|webm|ogg|pdf|zip|gz)\$ {
        expires 6M;
        add_header Cache-Control "public, immutable" always;
        access_log off;
        try_files \$uri =404;
    }

    # --- Abuse protection: zones are defined in $BAMBOO_NGINX_LIMITS_FILE ---
    limit_req zone=bamboo_req burst=40 nodelay;
    limit_conn bamboo_conn 32;
    limit_req_status 429;
    limit_conn_status 429;

    location / {
        try_files \$uri \$uri/ =404;
    }
EOF
    return 0
}

nginx_emit_http_serve_block() {
    local domain="$1" root logs names
    root="$(workspace_public "$domain")"
    logs="$(workspace_logs "$domain")"
    names="$(nginx_server_names "$domain")"
    cat <<EOF
# Managed by $BAMBOO_PROG_NAME — regenerated by 'add' and 'ssl'.
# Site: $domain   Mode: HTTP-only (no certificate yet)
server {
    listen 80;
    listen [::]:80;
    server_name $names;

    root $root;
    index index.html index.htm;

    access_log $logs/access.log;
    error_log  $logs/error.log warn;

    client_max_body_size $BAMBOO_MAX_BODY_SIZE;

$(nginx_emit_security_headers 0)
$(nginx_emit_common_locations "$domain")
}
EOF
    return 0
}

nginx_emit_redirect_block() {
    local domain="$1" root logs names
    root="$(workspace_public "$domain")"
    logs="$(workspace_logs "$domain")"
    names="$(nginx_server_names "$domain")"
    cat <<EOF
# Managed by $BAMBOO_PROG_NAME — regenerated by 'add' and 'ssl'.
# Site: $domain   Mode: HTTPS (port 80 redirects, ACME stays open)
server {
    listen 80;
    listen [::]:80;
    server_name $names;

    access_log $logs/access.log;
    error_log  $logs/error.log warn;

    location ^~ /.well-known/acme-challenge/ {
        root $root;
        default_type "text/plain";
        allow all;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
EOF
    return 0
}

nginx_emit_https_block() {
    local domain="$1" root logs names live
    root="$(workspace_public "$domain")"
    logs="$(workspace_logs "$domain")"
    names="$(nginx_server_names "$domain")"
    live="$BAMBOO_LETSENCRYPT_LIVE/$domain"

    printf '\n# --- HTTPS: %s ---\n' "$domain"
    printf 'server {\n'
    nginx_http2_listen_lines
    printf '    server_name %s;\n\n' "$names"
    printf '    ssl_certificate     %s/fullchain.pem;\n' "$live"
    printf '    ssl_certificate_key %s/privkey.pem;\n' "$live"
    if [ -f "$BAMBOO_LETSENCRYPT_DIR/options-ssl-nginx.conf" ]; then
        # Certbot's tuned parameters file already sets protocols and session
        # settings; duplicating them here would be a hard nginx error.
        printf '    include %s/options-ssl-nginx.conf;\n' "$BAMBOO_LETSENCRYPT_DIR"
    else
        printf '    ssl_protocols TLSv1.2 TLSv1.3;\n'
        printf '    ssl_prefer_server_ciphers off;\n'
        printf '    ssl_session_cache shared:SSL:10m;\n'
        printf '    ssl_session_timeout 1d;\n'
        printf '    ssl_session_tickets off;\n'
    fi
    if [ -f "$BAMBOO_LETSENCRYPT_DIR/ssl-dhparams.pem" ]; then
        printf '    ssl_dhparam %s/ssl-dhparams.pem;\n' "$BAMBOO_LETSENCRYPT_DIR"
    fi
    printf '\n    root %s;\n' "$root"
    printf '    index index.html index.htm;\n\n'
    printf '    access_log %s/access.log;\n' "$logs"
    printf '    error_log  %s/error.log warn;\n\n' "$logs"
    printf '    client_max_body_size %s;\n\n' "$BAMBOO_MAX_BODY_SIZE"
    nginx_emit_security_headers 1
    nginx_emit_common_locations "$domain"
    printf '}\n'
    return 0
}

nginx_server_names() {
    # Prefer the names the certificate actually covers, so server_name always
    # matches the certificate; fall back to the bare domain.
    local domain="$1" names=''
    if ssl_cert_exists "$domain"; then
        names="$(ssl_cert_names "$domain")"
    fi
    [ -n "$names" ] || names="$domain"
    printf '%s' "$names"
}

nginx_write_site() {
    # nginx_write_site <domain> <http|https>
    local domain="$1" mode="$2" conf
    conf="$(workspace_conf "$domain")"
    if bamboo_is_dry_run; then
        log_info "[dry-run] would write the $mode configuration to $conf"
        return 0
    fi
    # Keep the previously generated version next to the file for easy recovery.
    if [ -f "$conf" ]; then
        cp -p "$conf" "$conf.bak" 2>/dev/null || true
    fi
    case "$mode" in
        http)  { nginx_emit_http_serve_block "$domain"; } | atomic_write "$conf" ;;
        https) { nginx_emit_redirect_block "$domain"; nginx_emit_https_block "$domain"; } | atomic_write "$conf" ;;
        *) die "Internal error: unknown Nginx mode '$mode'." ;;
    esac
    bamboo_chmod 0644 "$conf" 2>/dev/null || true
    log_debug "Wrote $conf ($mode)"
    return 0
}

nginx_wire_symlinks() {
    local domain="$1" conf avail enabled
    conf="$(workspace_conf "$domain")"
    avail="$BAMBOO_NGINX_AVAILABLE/$domain.conf"
    enabled="$BAMBOO_NGINX_ENABLED/$domain.conf"

    if bamboo_is_dry_run; then
        log_info "[dry-run] would link $avail -> $conf and $enabled -> ../sites-available/$domain.conf"
        return 0
    fi
    mkdir -p "$BAMBOO_NGINX_AVAILABLE" "$BAMBOO_NGINX_ENABLED" \
        || die "Unable to create the Nginx sites-available/sites-enabled directories."

    # Never clobber a config the operator wrote by hand; move it aside.
    local target bak
    for target in "$avail" "$enabled"; do
        if [ -e "$target" ] && [ ! -L "$target" ]; then
            bak="$target.bak.$(date '+%Y%m%d%H%M%S')"
            mv -f "$target" "$bak" || die "Unable to move $target aside."
            log_warn "Existing $target moved to $bak"
        fi
    done

    ln -sfn "$conf" "$avail" || die "Unable to create the symlink $avail"
    ln -sfn "../sites-available/$domain.conf" "$enabled" || die "Unable to create the symlink $enabled"
    log_debug "Linked $enabled -> sites-available/$domain.conf"
    return 0
}

nginx_unwire_symlinks() {
    # nginx_unwire_symlinks <domain> [also_remove_sites_available]
    # Only removes links that point where we expect, never a file we did not
    # create.
    local domain="$1" also_available="${2:-1}" target=''
    local avail="$BAMBOO_NGINX_AVAILABLE/$domain.conf"
    local enabled="$BAMBOO_NGINX_ENABLED/$domain.conf"

    if [ -L "$enabled" ]; then
        target="$(readlink "$enabled")"
        case "$target" in
            *"$domain.conf") bamboo_run rm -f "$enabled" ;;
            *) log_warn "Not removing $enabled: it does not point at $domain.conf." ;;
        esac
    fi
    if [ "$also_available" = "1" ] && [ -L "$avail" ]; then
        target="$(readlink "$avail")"
        if [ "$target" = "$(workspace_conf "$domain")" ]; then
            bamboo_run rm -f "$avail"
        else
            log_warn "Not removing $avail: it does not point at the workspace config."
        fi
    fi
    return 0
}

nginx_apply_site() {
    # Render, wire and reload — with rollback if nginx -t rejects the result.
    local domain="$1" mode="$2" conf prev='' had_prev=0

    if bamboo_is_dry_run; then
        log_info "[dry-run] would render, test and reload the $mode configuration for $domain"
        return 0
    fi
    if [ "$mode" = "https" ] && ! ssl_cert_exists "$domain"; then
        die "No certificate for $domain yet — cannot serve HTTPS. Run: sudo $BAMBOO_PROG_NAME ssl $domain"
    fi

    nginx_ensure_limits
    mkdir -p "$(workspace_nginx "$domain")" || die "Unable to create $(workspace_nginx "$domain")"
    conf="$(workspace_conf "$domain")"

    if [ -f "$conf" ]; then
        bamboo_ensure_tmpdir
        prev="$(mktemp "$BAMBOO_TMPDIR/previous-conf.XXXXXX")"
        cp -p "$conf" "$prev"
        had_prev=1
    fi

    nginx_write_site "$domain" "$mode"
    nginx_wire_symlinks "$domain"

    if bamboo_nginx_test; then
        [ "$had_prev" = "1" ] && rm -f "$prev"
        bamboo_service_reload nginx
        log_ok "Nginx is serving $domain in $mode mode."
        return 0
    fi

    log_error "nginx -t rejected the $mode configuration for $domain."
    if [ "$had_prev" = "1" ]; then
        mv -f "$prev" "$conf" || die "Unable to restore $conf — inspect it with: sudo $BAMBOO_PROG_NAME edit $domain"
        log_warn 'Restored the previous configuration.'
        if bamboo_nginx_test; then
            log_ok 'Rollback verified — Nginx keeps running the previous config.'
        else
            log_error "The rollback also fails nginx -t — inspect it with: sudo $BAMBOO_PROG_NAME edit $domain"
        fi
    else
        nginx_unwire_symlinks "$domain" 1
        log_warn 'Removed the new configuration (there was nothing to roll back to).'
        bamboo_nginx_test || true
    fi
    die "Aborted: the $mode configuration for $domain was not applied."
}

nginx_set_mode() {
    # nginx_set_mode <domain> <http|https>
    local domain="$1" mode="$2" conf
    conf="$(workspace_conf "$domain")"
    if [ "$mode" = "https" ] && [ -f "$conf" ] && ! nginx_is_https "$domain" && ! bamboo_is_dry_run; then
        cp -p "$conf" "$conf.pre-https" 2>/dev/null || true
    fi
    nginx_apply_site "$domain" "$mode"
    return 0
}

nginx_remove_site() {
    # Disable first, verify, reload, then delete the links and the config.
    local domain="$1"
    if bamboo_is_dry_run; then
        log_info "[dry-run] would disable and remove the Nginx configuration for $domain"
        return 0
    fi
    nginx_unwire_symlinks "$domain" 0
    if ! bamboo_nginx_test; then
        log_error "nginx -t failed after disabling $domain — re-enabling it."
        nginx_wire_symlinks "$domain"
        die "Aborted: the Nginx configuration for $domain was left untouched."
    fi
    bamboo_service_reload nginx
    log_ok "Nginx no longer serves $domain."
    nginx_unwire_symlinks "$domain" 1
    return 0
}

nginx_is_https() {
    local domain="$1" conf
    conf="$(workspace_conf "$domain")"
    [ -f "$conf" ] || return 1
    grep -q 'listen 443 ssl' "$conf" >/dev/null 2>&1 || return 1
    return 0
}

nginx_site_enabled() {
    local domain="$1"
    local enabled="$BAMBOO_NGINX_ENABLED/$domain.conf"
    [ -L "$enabled" ] || [ -e "$enabled" ]
}

nginx_site_mode() {
    # Prints: https | http | disabled | missing
    local domain="$1" conf
    conf="$(workspace_conf "$domain")"
    if [ ! -f "$conf" ]; then
        printf 'missing'
        return 0
    fi
    if ! nginx_site_enabled "$domain"; then
        printf 'disabled'
        return 0
    fi
    if nginx_is_https "$domain"; then
        printf 'https'
    else
        printf 'http'
    fi
    return 0
}
